{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "demoabc.serviceAccountName" . }}
  labels:
{{ include "demoabc.labels" . | indent 4 }}
{{- end -}}
